export const blueIds = {
  Actor: 'CN5efWVizJbRsMCw8YWRfT2q9vM9XfeGDN9wFvYcvMnQ',
  'Chat Message': 'AkUKoKY1hHY1CytCrAXDPKCd4md1QGmn1WNcQtWBsyAD',
  'Composite Timeline Channel': '9UrxZie5wEmEFZadY2YwAyygwNBzrPDLK5MGoFLfBBfW',
  'Document Status': '58B8orsFkxxy7bWqjLXJmtBs2b5rwnNQNbeoAbGhPkJc',
  Event: '5Wz4G9qcnBJnntYRkz4dgLK5bSuoMpYJZj4j5M59z4we',
  'Inform User About Pending Action':
    '8Akr9sdTkxBqMYWSGh8gHgoXQQeYEPfhV4s8fXeKTd9W',
  'JavaScript Code': 'DMrw2BSxyuQZai4UvitEY4YUp13ebP4prXyY8ZrZbM4Q',
  'Lifecycle Event': '5YZEAtUaHhNfnVnwtSsyBnBakpcSwdL75UcgtrtnqeYn',
  Operation: 'BoAiqVUZv9Fum3wFqaX2JnQMBHJLxJSo2V9U2UBmCfsC',
  'Operation Request': 'HM4Ku4LFcjC5MxnhPMRwQ8w3BbHmJKKZfHTTzsd4jbJq',
  Request: '8f9UhHMbRe62sFgzQVheToaJPYi7t7HPNVvpQTbqfL5n',
  Response: '36epvrpVHZLjapbeZsNodz2NDnm7XZeNZcnkWHgkP1pp',
  'Sequential Workflow': '7X3LkN54Yp88JgZbppPhP6hM3Jqiqv8Z2i4kS7phXtQe',
  'Sequential Workflow Operation':
    'CGdxkNjPcsdescqLPz6SNLsMyak6demQQr7RoKNHbCyv',
  'Sequential Workflow Step': 'HYsLiqsqk7t98d5fK6YxKEQGeqBaHNVjM4rRNdxK4yUW',
  'Status Change': 'C48nKSkbxraMSv4gCiGYVHKFjmtK12k63Yasn95zknWE',
  'Status Completed': 'EhPFqrRCreg7StsZEcW8fRQ1FQVdqYSsMSis2CHHJZ1G',
  'Status Failed': 'Guus3kHbivXvy5G93yhiKs3Pc8sxCc4XVvSo7CqLsQEc',
  'Status In Progress': '56Lhu3Z2oF3kuYG41eZAK8TvgVtRNevkbRi4D31kKWZm',
  'Status Pending': 'ETAPjwZVyYEfPUWvXkCWAuybBhYUayg4hKC2V7mLXmsv',
  Timeline: '3Ge54FsGJaaeZmm8nTKJdS6HVdYhiR3g18fDwg3Ev1Sa',
  'Timeline Channel': 'AAhZviH8oyst6aKJKUNJS99Q9MnMqtb9DuNRfqv4yFQN',
  'Timeline Entry': 'EzDiC9Frs8V5yQBMtDYh1DobVnWtWpFemXDX5fGUULBn',
  'Trigger Event': 'GxUtWr3eH9a6YQeioQkujEnsPjD5s9RU8ZhEfmsV1vuU',
  'Update Document': 'BnnNLCnKF49TUJ1bRfZ5rSMaFw8SVfUNfnE4kJFG7HtM',
} as const;
