export const blueIds = {
  'Trigger Event': 'BWBJFxM7DtorfwMewvrfn3938VBCa3seKXTkkfpCwrQ1',
  'Lifecycle Event Channel': '3pjhMs7CnYrsz5xQni3PJ8z94L6CVMVGwEaLom5MZRaG',
  'Channel Event Checkpoint': 'GWGpN9tAX5i3MUic8NhrfRtKDh9mz6dxBys8NXyPYXZf',
  Operation: 'APkQmnhBWzQzpZAPHgyHeVm9QK8geARgVFg6418oFH1C',
  'Sequential Workflow Operation':
    '25oL2pyz4VZKCzA4CeRNjv2ixAL4EpMsDaJj4UyEW2gF',
  'Composite Timeline Channel': 'ABs3rYy5bpfHAF8DYi9tmcWPauhnLwfSAJvgmjG4av14',
  'Update Document': 'Bf61yTzodeWXWCTaiZqNNPf5Zbpet1ZUczvuewiL3rSZ',
  'Lifecycle Event': '3nViyQeU3RwjHJ7wtCoef7dwe7JPqYEvZUKEx4FohuP5',
  'Timeline Channel': 'xyBvDpt4fv9uqLMEvpJz4u6NDM9cpuanrmk1VsY7Z6V',
  'Document Processing Initiated':
    '75eYxjwaABUcTCuKCeg1Pf1jjwDarLnFLXtxERehWFCv',
  'Sequential Workflow Step': 'CvfSAWwJ4ZAMDNfum11cEcs54ECL8oszspkPKrMMY7xt',
  'Document Update Channel': 'ACyaz51YGg73NBZ1LFDw1vnZjzRCbPWgL7Y1XRKjXLKV',
  Channel: '23ZWQ6WWqFcyuoBDV9P8XaLk2oEwJtoQaPrkFFayZVqY',
  'Initialized Marker': '9Wgpr1kx18MaV1C6QraNbS2mYeapUhHh5SDAuNFTCHcf',
  'Inform User About Pending Action':
    'DiocsM4B3rE4LVAbdSf9WBKa8tdUSaDmvpPfNuBRHUxs',
  Marker: '3gJb4roGCuJQ1gibFXex6HoNjuTeiPvYRCquujAvg83t',
  'Process Embedded': '2eAkQahk1Ce5qC9Rzwkmc5eU1yYG3asRS21gBYePb4KE',
  'Document Update': 'EetjknS9cKPHHZuK93nvqNDFjJDsPLM7qsbyxLzuur7N',
  'Embedded Node Channel': '9FT814paTzhSQ3sRPUWoj7Qv5EeWGhXvhU5ebNpbkv2S',
  'Json Patch Entry': 'HdRLN3dEgUJH9Yp3HVH2gDPjG7hsYEAVfWoFuStGrvuu',
  'Sequential Workflow': 'AQYxXnq4Yr9kRhfQnvneuyHRyMzDHFiewF27EeqVy6du',
  Timeline: 'C7TsyShrDryZ121B2EJMKD9ui1ozmvTfGUkquRKkSvAP',
  'Timeline Entry': '3BfN3pzCyuWfyksE6P467WJEtYqAvUeC9LybJA6iXVtL',
  'State Change': 'Ayf4DPoE8H7JWxE8CDM73T7GJdjey4jo4mUEDnenwzkN',
  Event: '3gtD3i9bgfhDat3VB53vrQpchWFn1McYe2ngSc3YLjar',
  'Chat Message': '51RV2uUTrvMb1P1u9pno6r4Ujbns9kBJRFbZrq45C6WS',
  'Operation Request': 'QQiMca4DR3UwxGceNoECDcKkeQQuF7Y8Noh2DDQTUFv',
  'JavaScript Code': 'CbkaaimMgTw2L5AP6bVWVKVArHkkrKuJxu6Uo4o6Piwr',
} as const;
