export const blueIds = {
  'Agreed Upon Simulated Event': '6AxdkLN2PgdzYJhojHRH6rt3oTAoifrJYikYvNHMbw2t',
  'All Events External Contract Subscription':
    'JCUV8S58BvgAr8LzsHxPRtm72PsxPvgzZGLiqgwRM6xS',
  'Assistant Task': '8ChHz6j1f3G1hnq11UPgM6Gm61viW2uJWkBPueWXP4dc',
  'Assistant Task Ready Event': 'CUKPAHgXTYtEUwyT172ejy694PR41rsy5VG1n5Wfsu2p',
  Contract: '6j4rVp2aAm35U7dvbYPQsdi82JUpRPb1kTfkYrhHxvqE',
  'Contract Initialization Event':
    '3uzSCGkrdX4hTFGuLbyZES7NQmiuFskCpUy572GxNQuC',
  'Contract Instance': 'WtsCXffC75An6E8EMfR4VMZvJ9bXzCPDAsD5hncpZ97',
  'Contract Processing Event': 'CzZuis9rsRZdmS5nzdgp9RtTknQbs8Jxxp95djCmbAW1',
  'Contract Subscription': 'BnzvPoTRbeT8JmH6rDn3Sh9f2gfCNBTm58WVxdUcorXr',
  'Contract Update Action': '94birjcTV223qXtC1aq4xZRWfvxrzh9a1dF99YV5wWwr',
  'Contract Update Event': '2bsu7Nx1vCXquU24RUXcc5b8tHrNgve26MXia4vUBuvN',
  'Expect Event Step': '3UXhfjDZ8EMopVJrDxS8Gf2USfLZvzFGpzyzconyzAkm',
  'External Contract': 'A5wPMJi6naaUtbmo5iPqUVG5Q8Wg5r68WERCarJctSoK',
  'Fatal Error Event': '4cSr9TtEebEMxghBQD9ybAW6Tf6TUGGLG45fZxkxJQaP',
  'Generic Contract': '9Wpm7tPqAYoaS45ky18v61WBy6KdR78awSTv8wX8AprN',
  'Initial Timeline Message': '7rhXztX94ehngtETBBsq4pY3e1siDPjd7xrV1y6rrtye',
  'Initialize Local Contract Step':
    'FF88BRKtRXQ2cCCBR28cFUB5mHdPsWjj8gVBgz4VmQm7',
  'Initiate Contract Action': 'EmyutwPX7UgfUayYoZqFAxjNY6DYoNoj67Hqg36GACym',
  'Initiate Contract Processing Action':
    'E64ZQaX4sFUD3CsVpb7bWZwBznbNDsJCJtRxux4FdWGm',
  'JavaScript Code Step': 'CFKAD5Up8XpNyPHwRBEwiwSUdfFUoGqVVsW29k6te88p',
  'Json Patch Entry': 'EnUQeMiMa2wHFW3JbeSPvdgfpL6qZYCR29m3SfeHsKSY',
  'Local Contract': 'Cwqs1QterdmwBAARMViJsepJAdYLGdhLHHg1u7awytAN',
  'Local Contract Subscription': 'CTeVLJrK2kNQ4WhC7nd7JrsDcQtyEU9oBHgE23sEmoTK',
  Participant: 'ATbZ8UAASUy2PaooqZx6CE9giEfKcvrs3nQPcK5jTmBJ',
  'Perform Contract Action': '4H8MC7tvfQR5MnuRimNqScZ1RWjwDrZza7uuHWUmMVQj',
  'Timeline Entry': '5BDj3UbH6nUPh6bUQ9vfEchjV2vGLMwhd1FJ5UYaRcos',
  'Trigger Event Step': '6sdEGwtrVJhdto5CsDzm81YrJtHTZrdsenZkyCWJLniU',
  'Update Step': 'DpdjTNXQdgWGxDyB1LLUNFvxSNNM9L9qGMoKZxzYMDoB',
  Workflow: 'Fq9xM7HgfQRq2zZWc2mKMXBhbwADtBBtas7y9FTRuyvb',
  'Workflow Function': '66oteHvnKcpRvS1ty6qND1keob9PJVakKxjTQPQY8YFA',
  'Workflow Function Step': 'EZjDfHEnvvwhP14FXdzLSBXBW9BcanYefW9mRfZNLh7D',
  'Workflow Instance': 'HX3J23DpxGanyzSHZtY1VGNno4qapcHUkGW2Ha2WYf92',
  'Workflow Instance Started Event':
    'Gn7ajBNyZhKNohLbfZhnYPs5s7NmtZR3RxJv1rGGZjg8',
  'Workflow Step': 'H5YcJM1fBf57BjYjc7hXbotGh5RuD8bwXLTVY4PA353u',
} as const;
