name: Prepare Release

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to prepare release from'
        required: false
        default: 'main'
        type: string
  push:
    branches:
      - testing

jobs:
  prepare:
    name: Prepare Release
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 10
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.branch || github.ref }}

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps
        shell: bash

      - name: Print Environment Info
        run: npx nx report
        shell: bash

      - name: Prepare Release
        run: npx nx release --first-release --skip-publish --dry-run
        shell: bash
